services:
  db:
    image: postgres:16-alpine
    container_name: hose_management_db
    restart: always
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
