# Generated by Django 6.1.1 on 2026-09-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=155)),
                ('year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(choices=[('buffalo', 'Buffalo Milk'), ('cow', 'Cow Milk')], max_length=155)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MilkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('milk_type', models.CharField(choices=[('buffalo', 'Buffalo Milk'), ('cow', 'Cow Milk')], max_length=155)),
                ('quantity_litres', models.DecimalField(choices=[(0.25, '250ml'), (0.5, '500ml'), (0.75, '750ml'), (1.0, '1L'), (1.5, '1.5L'), (2.0, '2L')], decimal_places=2, max_digits=6)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
