# Generated by Django 6.1.1 on 2026-09-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='date',
            field=models.DateField(),
        ),
    ]
