# Generated by Django 6.1.1 on 2026-10-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_alter_milkentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkentry',
            name='note',
            field=models.CharField(blank=True, help_text='Optional note for this entry', max_length=255, null=True),
        ),
    ]
